name: isabel
favicon: null
layout_spectrum: 0.362966516520828
typography_spectrum: 0.34656916465610266
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.533697847276926
  lightness: 0.5514030365739018
  saturation: 0.7374113178811967
  rhythmicContrast: 0.40590745909139514
purpose: []
